apiVersion: v2
name: sealed-secrets
version: 2.18.0
description: Sealed Secrets controller
dependencies:
  - name: sealed-secrets
    version: 2.18.1
    repository: https://bitnami-labs.github.io/sealed-secrets
