apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mylittlesecret
  namespace: argocd
spec:
  encryptedData:
    lol: AgBMVD3gmMDUx7pYq6UayuTva8imTDO7x6K64vZUNgNTxvcz5qsf07TP7nteuCvjWI85rXO1MJXRBS5I/9UXFaVtJqJmcE0wiKQorHpAp8nkXLcJY0AVqv6/OFlD1g6kFVRyP3vD7O7fbntUAoU9lBizqxJ3/+QtsRy+fxZYUcLNt0eU5/joRvBwgb5Z6FLKhaV+Z8D0AnqLnhaTkgMWS61X+rRqGIGGM6awkbpANuwRg8UBQ2oPh/eBr2L+KDdvwRvvLgon5OLUXT7SU+saUU/j3OLsAYFFJly4ZcTHASUd5cdK+nY+cQe0/pDtZkvUagudGGLOn2MZW8+WlLUuDxABePBH/yu1BpMsNsMxMdxDr1SNCyCYIcSaJoq+uvSRjS0QXxtTD6dYyknvks5cSBQ0SQrvrX5p2sdukZlABtWl5y2mLvTnU18Bq8bxo2qAAF8gpnDasJb4y5Mh1AITMOFrJVi7fEot0J1nPKH14qeojoXwlgEvI3Yvyerh76RTkZdHxONIYSkyFiXShw4mDCLR1PLFmfIov7BJJbfu2t7+9P1o8oH8OrGqKkfY0esZJOctR/M4+jbMnLdLeOp3Se5bHTVgrSjsTIwN3ZTCNSDOlsj6hgxg2aQ2cCkFzrZcF6xeOxBZWnXGQ3snqQcMohtO6ht4IJF4A0FI/HYouyngm87M3+OGoE+yjAb8V9dj7OYy1U1zNYseQ8sk/gojiGU=
  template:
    metadata:
      name: mylittlesecret
      namespace: demo
